### ISSUE TITLE
how to open

### ISSUE THREAD

**Issue by Hughesi-YT** [SebLague/Fluid-Sim#1]
i have downloaded the file, how do i open it to do the simulation (im new to GitHub sry)

**Comment by SebLague** [comment]
You'll need to install the Unity editor and open it in there

**Comment by potatochipsnotincluded** [comment]
and unzip the file!

**Comment by potatochipsnotincluded** [comment]
you can use the open button in the unity hub and then find the folder you unzipped, and click on it
