### ISSUE TITLE
Hello, I have a question about the project that doesn't seem to work properly when I build it. (especally Test A, B)

### ISSUE THREAD

**Issue by hyunsoojjang** [SebLague/Fluid-Sim#11]
Hello! I've received a project and I'm testing it. I have a question – when I build and run Test A, B, and C scenes, the screen appears black in scenes except Test C scene. I'm curious if there are any adjustments needed in project settings or graphic configurations. Thank you!

using unity 2022.3.8

**Comment by austinplane** [comment]
@hyunsoojjang What was the fix for this issue? I am encountering a similar problem. Thank you.

**Comment by hyunsoojjang** [comment]
as i remember it is related to OnValidate func. it is running on only unity editor . check that func .Thanks

-----Original Message-----
보낸사람: ***@***.***>
받는사람: ***@***.***>
참조: ***@***.***>, ***@***.***>
날짜: 2024. 5. 4 01:29:20
제목: Re: [SebLague/Fluid-Sim] Hello, I have a question about the project that doesn't seem to work properly when I build it. (especally Test A, B) (Issue #11)

@hyunsoojjang What was the fix for this issue? I am encountering a similar problem. Thank you.
