### ISSUE TITLE
Black screen on build

### ISSUE THREAD

**Issue by austinplane** [SebLague/Fluid-Sim#12]
When I attempt to build using the 2D scenes, I only see a black screen in-game. When I build the 3D scene, spheres are rendered but not in color. Everything works perfectly in the editor. I have tried adding the various shaders to the "Always Included Shaders" list, but this has no effect.

Any explanation for this behavior would be appreciated.

**Comment by INedelcu** [comment]
Initialize needsUpdate to true in ParticleDisplay3D.cs 😊

**Comment by austinplane** [comment]
Thank you... omg. Was driving me crazy.

**Comment by INedelcu** [comment]
No problem. Probably the same issue with needsUpdate here:

https://github.com/SebLague/Fluid-Sim/blob/main/Assets/Scripts/Sim%202D/Display/ParticleDisplayGPU.cs#L16

Just set it to true.
