### ISSUE TITLE
Incorrect Unity version at the project's README

### ISSUE THREAD

**Issue by muhammetssen** [SebLague/Fluid-Sim#2]
Hello, I've noticed a discrepancy between the Unity version mentioned in the project's README (Unity 2021.3) and the version specified in ProjectSettings/ProjectVersion.txt (m_EditorVersion: 2022.3.8f1).

Cannot wait to dig around and learn more about shaders! I really appreciate the way you simplify complex concepts, making them easy to understand and fun to follow ❤️

**Comment by SebLague** [comment]
Thank you, I changed it to 2022.3 :)
