### ISSUE TITLE
Calculate Offsets Behavior Doesn't Match Description

### ISSUE THREAD

**Issue by cmhhelgeson** [SebLague/Fluid-Sim#8]
The description of the CalculateOffsets Compute Function indicates that an array of sorted keys {0001223333} would produce an array of offsets {0003446666}. However, this behavior would seem to be incorrect, for two reasons.
A. Assignments only occur when key and prevKey do not equal each other, and not for each index of the numParticles sized offsets buffer.
B. The offsets buffer is assigned at the index of the key rather than the index of the invocation.

In actuality, based on the behavior in the program, the output of the offsets buffer would look more like {03460000000}. I'm not sure whether this is an error with the description or an error with the program itself.

EDIT: Based on the code in the other shaders, it would seem like the offsets buffer is only indexed by key, with the buffer size to numParticles to account for edge cases where every key in SpatialIndices is unique. Accordingly, I think this is just an issue with the current description of the shader's behavior.

**Comment by SebLague** [comment]
Fixed, thank you! Unclear what in the world I was thinking when I wrote that comment.
